# mysql 配置
mysql:
  host: 175.24.205.216
  port: 3306
  username: awesome_db
  password: "m3HsjCPhTM5aEYxJ"
  db_name: awesome_db
  #最小连接数
  pool_min_idle: 8
  #最大连接数
  pool_max_open: 32
  #连接超时时间单位秒
  timeout_seconds: 15

application:
  server:
    port: 7878

snow_flake_id_worker:
  work_id: 5
  data_center_id: 3